### ISSUE TITLE
Cannot add backorderable products to cart in admin

### ISSUE THREAD

**Issue by mdamian322** [solidusio/solidus#2522] opened 2018-01-23 18:55 UTC
**Steps to reproduce**
1. Have a product that has 0 stock but is backorderable
2. Create a new order in admin
3. On the cart tab, search for that product in order to add it to the cart
4. No results come up

**Expected behavior**
I expect the product to come up in search so I can add it to the customer's cart since it's backorderable. On the frontend, the customer is able to purchase it just fine. 

**Actual behavior**
The product does not show up and I am not able to add it to the cart.

System configuration
2.4

**Comment by jhawthorn** [comment] 2018-01-23 23:19
Can confirm this issue. The problem is that most of our admin variant selectors use `in_stock_only: true`. Our terminology in the API and core is that [`in_stock`](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/variant.rb#L97) means essentially `count_on_hand  > 0 || !track_inventory?`.

We should introduce a new scope to mean any variant which we could put in an order: `count_on_hand  > 0 || backordered? || !track_inventory?`.

I have no idea what to call this. Any suggestions?

**Comment by skukx** [comment] 2018-01-24 22:41
I like the idea of `can_supply?` or close to that and the name makes sense for the functionality it will provide.  Items that are in stock, or backorderable, or don't require tracking. Possibly add a scope to the variant called `suppliable` to go with the `in_stock` scope.

```ruby
Spree::Variant.in_stock
Spree::Variant.suppliable
```

See: https://github.com/solidusio/solidus/blob/master/api/app/controllers/spree/api/variants_controller.rb#L70

**Comment by jhawthorn** [comment] 2018-02-01 18:52
I believe this is fixed by #2536

**Closed** 2018-02-01 18:52 UTC
Labels: bug
