### ISSUE TITLE
Solidus migrations not creating tables with bigint primary keys

### ISSUE THREAD

**Issue by AdnanTheExcellent** [solidusio/solidus#2828] opened 2018-08-13 16:32 UTC
With rails 5.1 onward, primary keys now default to bigints in Rails. Solidus 2.6 requires 5.1+, but since the migrations are set to rails 5.0 migrations, the tables created don't have bigint primary keys when creating a db from the migrations in a fresh solidus rails app. Should we expect the migrations to create tables with bigint primary keys? 

A quick solution is to set all the past migrations to rails 5.1 migrations.

**Comment by kennyadsl** [comment] 2018-08-16 22:17
Duplicate of #2807, let's discuss there!

**Closed by kennyadsl** 2018-08-16 22:17 UTC
