### ISSUE TITLE
Undefined method `arity`

### ISSUE THREAD

**Issue by papebarka** [solidusio/solidus#3964] opened 2021-02-26 16:28 UTC
**Solidus Version**: 2.11.4

**Ruby on Rails Version**: 6.1.1

**Current behavior**
After starting the server, I'm getting a: NoMethodError in Spree::Home#index

undefined method `arity' for {:class_name=>"Spree::Taxon", :foreign_key=>"parent_id", :primary_key=>"id", :counter_cache=>false, :inverse_of=>:children, :touch=>false, :optional=>true}:Hash

**Screenshots**
<img width="1135" alt="Capture d’écran 2021-02-26 à 16 15 59" src="https://user-images.githubusercontent.com/13225725/109326268-dcac6580-784e-11eb-984d-8e9501c0737e.png">

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome

**Comment by jarednorman** [comment] 2021-02-26 17:10
This is a duplicate of #3953.

The fix for this is on the `v2.11` branch but has not been released. @kennyadsl left a comment [here](https://github.com/solidusio/solidus/issues/3953#issuecomment-786196691) with the temporary fix until a new version is released.

**Closed by jarednorman** 2021-02-26 17:10 UTC

**Comment by papebarka** [comment] 2021-02-27 00:20
> This is a duplicate of #3953.
> 
> The fix for this is on the `v2.11` branch but has not been released. @kennyadsl left a comment [here](https://github.com/solidusio/solidus/issues/3953#issuecomment-786196691) with the temporary fix until a new version is released.


There is a new error after changing the gem as specified: undefined method `escape' for URI:Module

<img width="1056" alt="Capture d’écran 2021-02-27 à 00 18 05" src="https://user-images.githubusercontent.com/13225725/109368609-99bfb180-7891-11eb-802c-9795756bac46.png">

**Comment by jarednorman** [comment] 2021-02-27 01:02
If you're having trouble getting Solidus running, you're best off heading over to [our troubleshooting board](https://github.com/solidusio/solidus/discussions/categories/troubleshooting) and posting there with some more information about that exception, like the stack trace and versions of Ruby and Rails that you are using. I'm pretty sure the code you referenced isn't in Solidus.
