### ISSUE TITLE
Can't destroy a cancelled order

### ISSUE THREAD

**Issue by saroar** [solidusio/solidus#695] opened 2016-01-14 19:49 UTC
When i delete order direct it work but after cancel order i cant delete order just show me red flash thats all i am not sure it my mistake or it bug so please let me what you think if it my mistake sorry for that :) if not please hope it will be correct next update and this solidus don't have default image not this too thanks

**Comment by jhawthorn** [comment] 2016-01-14 22:36
I can verify that you aren't able to destroy a cancelled order.

Seems like this is the culprit:
https://github.com/solidusio/solidus/blob/master/core/app/models/spree/inventory_unit.rb#L136-L139

Seems by design that we don't want to be able to destroy cancelled units, possibly to ensure we preserve data.

**Comment by jemagee** [comment] 2016-02-07 00:50
But is a cancelled order data that needs to be preserved?  Is there reporting that segregates out cancelled orders?  Cancelled orders are different than returns, they are basically orders that never happened.  So why are they being saved?

**Comment by mamhoff** [comment] 2016-02-07 14:20
Canceled orders might have associated payments (if you have the customer pay on completing checkout). In that case, "canceling" an order does not mean "pretend it never happened". It means: Restock all the inventory and refund the money. Your accountants will thank you for keeping the record.

**Comment by swcraig** [comment] 2017-08-25 19:06
@mamhoff's justification makes sense. May we close this?

**Comment by tvdeyen** [comment] 2017-08-25 19:42
Yes.

**Closed by tvdeyen** 2017-08-25 19:42 UTC
