### ISSUE TITLE
Stock::Coordinator incorrectly splits packages

### ISSUE THREAD

**Issue by adaddeo** [solidusio/solidus#1366] opened 2016-08-02 18:21 UTC
On a 1.3 sandbox store:
1. In the admin, create a new order
2. Add 1 unit of any item
3. Update the quantity of item to 2
4. Enter customer details (anything will work) and update
5. Two shipments are created, each with 1 item

**Comment by jhawthorn** [comment] 2016-08-03 17:28
Confirmed. Looks like it's realated to an `OrderStockLocation` record being careted, which are used to configure packages specifically for one location.

**Comment by DanielePalombo** [comment] 2016-09-02 16:22
@jhawthorn i'm working on this issue, I'm almost done

**Comment by DanielePalombo** [comment] 2016-09-12 08:39
@adaddeo Have you try if my PR resolve your issue?

**Comment by jhawthorn** [comment] 2017-02-17 21:41
This should be fixed by #1709, which bypasses the "location configured package" feature, which is what caused the separate shipments.

**Closed by jhawthorn** 2017-02-17 21:41 UTC
Labels: bug
