### ISSUE TITLE
Inconsistent Order Lookup Between Controllers

### ISSUE THREAD

**Issue by jumph4x** [solidusio/solidus#3467] opened 2019-12-30 21:32 UTC
Hey folks,

I am looking for some insight here, perhaps you can help me. We ran into a case in production where an order shows up in the cart but upon trying to proceed with checkout, no order is found and the user is redirected back to the cart. 

This is fundamentally because in `Spree::OrdersController#edit`:
https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/orders_controller.rb#L42

```
@order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
```

However, in `Spree::CheckoutController#load_order`: 
https://github.com/solidusio/solidus/blob/master/frontend/app/controllers/spree/checkout_controller.rb#L136
``
@order = current_order
``

If we unpack `current_order` behavior further, you will see it uses a different query to load:
https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/order.rb#L86

```
order = Spree::Order.incomplete.lock(options[:lock]).find_by(current_order_params)
```

and

```
        def current_order_params
          { currency: current_pricing_options.currency, guest_token: cookies.signed[:guest_token], store_id: current_store.id, user_id: try_spree_current_user.try(:id) }
        end
```

In our specific case, the miss was happening because we had a state with the Order have a non-nil `user_id` and the query kept asking for `nil` because the other session did not exist. 

**Solidus Version**:
`master`

**To Reproduce**
I do not have all of the specific to reproduce but am hoping for some insightful discussion.

**Current behavior**
Orders and Checkout controllers load orders differently. 

**Expected behavior**
I would expect them to abide by the same business logic and am curious why that's not the case. I understand this behavior is inherited from a much older Spree release, but hoping folks have extra insight. 

Thanks, y'all!

**Comment by jumph4x** [comment] 2019-12-30 21:33
Tag @wildbillcat

**Comment by kennyadsl** [comment] 2020-01-02 14:52
Thanks for reporting this issue @jumph4x! 

I think there's something odd happening here. I'm trying to replicate the issue using `user_id: nil` in `current_order_params` to retrieve an order with `user_id` set:

```
> current_order_params = {:currency=>"USD", :guest_token=>"4zjNc3Xn5s0XAOPbMtxroA", :store_id=>1, :user_id=>nil}

> Spree::Order.incomplete.lock(options[:lock]).find_by(current_order_params)
#<Spree::Order id: 1, number: "R341961968", item_total: 0.1e2, total: 0.1e2, state: "cart", adjustment_total: 0.0, user_id: 1, completed_at: nil, bill_address_id: 1, ship_addr
ess_id: 2, payment_total: 0.0, shipment_state: nil, payment_state: nil, email: "email1@example.com", special_instructions: nil, created_at: "2020-01-02 14:40:10", updated_at:
"2020-01-02 14:40:11", currency: "USD", last_ip_address: nil, created_by_id: nil, shipment_total: 0.0, additional_tax_total: 0.0, promo_total: 0.0, channel: "spree", included_
tax_total: 0.0, item_count: 1, approver_id: nil, approved_at: nil, confirmation_delivered: false, guest_token: "4zjNc3Xn5s0XAOPbMtxroA", canceled_at: nil, canceler_id: nil, st
ore_id: 1, approver_name: nil, frontend_viewable: true>
```

As you can see, the order is persisted with `user_id: 1` and it's correctly retrieved.

I think the issue is somewhere else; if you have any other details feel free to share.

**Comment by biximilien** [comment] 2020-01-03 02:43
I remember running into a similar issue just last week and wanted to open an issue to get some insight as well, then christmas happened. I don't exactly remember the problem but all the lines quoted by @jumph4x ring a bell. I think in my case the issue was with `current_order_params` because of some parameters not being found by `find_by`. Hope this helps!

**Comment by jumph4x** [comment] 2020-01-06 18:31
@kennyadsl that may very well be the case, I'll continue pursuing my own end of things, obviously.

But I do wonder why core maintains this behavior.

**Comment by kennyadsl** [comment] 2020-01-13 13:21
I'm taking a second look here, trying to understand through git history why that code is there. 

I think it comes from this PR https://github.com/spree/spree/pull/5441 which I don't fully understand and has no specs that could be useful to refactor that piece. 

I tend to agree that there's no reason to use a different method in the Order controller and if I got it correctly, checking `Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])` is also useless since `current_order` already perform that same check.

Also, I don't understand why we should initialize a new order with the `guest_token` of an existing order. `current_order` has its own way of creating a new order and we should probably adhere to that by just using:

```
current_order(create_order_if_necessary: true)
```

Maybe @BenMorganIO is still around and has some insights here?

**Comment by BenMorganIO** [comment] 2020-01-13 21:21
Oh dear, this is from a long time ago. If I remember right the team I was with had issues with finding the order from a guest.

```ruby
Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
```

That's pretty self-explanatory on what it's trying to achieve. I think when you go to edit an order (the cart page) we wanted to make sure that an order object existed for you. The order needed to be incomplete. Now the behavioural difference from `current_order(create_order_if_necessary: true)` and this guy is that no new row will be inserted into the DB. It just uses your guest token to initialize an empty object for further ruby code to work with.

**Comment by kennyadsl** [comment] 2020-01-14 08:46
@BenMorganIO thanks for taking the time to answer.

What I still do not get is that the same query to retrieve the guest token is performed in the `current_order` method here:

https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/controller_helpers/order.rb#L94

So, when we have:

```
@order = current_order || Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
```

if there is a record in the database it will be retrieved by `current_order`. If `current_order` is nil, there's no need to make the query again. 

Also, if there are no incomplete orders with that guest_token, my guess is that we need to create a new order with a totally new `guest_token` instead of initializing an order with the `guest_token` of another order. Do you recall any advantages of using an existing token instead of refreshing it?

**Comment by jumph4x** [comment] 2020-01-14 17:37
@kennyadsl I appreciate you taking the time to understand this one. 

It sounds like something that may have ended up in core to guard against a reproducible edge case.

**Comment by BenMorganIO** [comment] 2020-01-16 00:27
@kennyadsl in regards to refreshing the token instead of using an old one: might just be an oversight.

**Closed** 2020-03-18 15:51 UTC
