### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by luizfzarco** [solidusio/solidus#1470] opened 2016-09-25 23:49 UTC
I was trying to experiment with Solidus but could not one-click deploy to Heroku because of building problems (rails version):

`-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
       Fetching gem metadata from https://rubygems.org/...........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Resolving dependencies....
       Bundler could not find compatible versions for gem "rails":
       In Gemfile:
       rails (= 4.2.7.1)
       solidus was resolved to 2.1.0.alpha, which depends on
       solidus_core (= 2.1.0.alpha) was resolved to 2.1.0.alpha, which depends on
       rails (~> 5.0.0)
       Bundler Output: Fetching gem metadata from https://rubygems.org/...........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Resolving dependencies....
       Bundler could not find compatible versions for gem "rails":
       In Gemfile:
       rails (= 4.2.7.1)
       
       solidus was resolved to 2.1.0.alpha, which depends on
       solidus_core (= 2.1.0.alpha) was resolved to 2.1.0.alpha, which depends on
       rails (~> 5.0.0)
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed`

**Comment by jhawthorn** [comment] 2016-09-27 18:38
Duplicate of #1299

**Closed by jhawthorn** 2016-09-27 18:38 UTC

**Comment by jhawthorn** [comment] 2016-09-28 02:57
This should now be fixed.
