### ISSUE TITLE
Taxonomies: Edit view crashing

### ISSUE THREAD

**Issue by chris-barklem** [solidusio/solidus#1148] opened 2016-05-15 15:46 UTC
When creating a taxonomy the child is created with a node name of "New node" which requires editing to complete the creation.

Clicking the edit icon leads to rails crashing with the following error:
http://localhost:3000/admin/taxonomies/1/taxons/2/edit

`/Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:9: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '(' ....id), no_text: truebtn-primary', icon: 'globe' );@output_buf... ... ^ /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:9: syntax error, unexpected tIDENTIFIER, expecting ')' ... truebtn-primary', icon: 'globe' );@output_buffer.safe_appen... ... ^ /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:11: syntax error, unexpected tIDENTIFIER, expecting ')' ...axonomies_path, :icon => 'arrow-left' );@output_buffer.safe_... ... ^ /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:11: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '(' ...ies_path, :icon => 'arrow-left' );@output_buffer.safe_append... ... ^ /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:12: syntax error, unexpected '<', expecting ')' </li> ^ /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:24: unknown regexp options - dv /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:28: `$(' is not allowed as a global variable name /Users/barklem/.rvm/gems/ruby-2.3.1/gems/solidus_backend-1.2.2/app/views/spree/admin/taxons/edit.html.erb:28: syntax error, unexpected end-of-input, expecting ')' ...utput_buffer.safe_append=' $(document).ready(function() { ... ^`

Extracted source (around line #9):

```
<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_taxonomies_list), spree.admin_taxonomies_path, :icon => 'arrow-left' %>
  </li>
<% end %>
```

**Comment by mtylty** [comment] 2016-05-17 09:35
I was unable to reproduce this bug...

**Comment by CBarklem** [comment] 2016-05-17 10:25
Hi @jhawthorn fixed the issue within minutes. Seemed to be a bug in the globalize gem.

**Comment by jhawthorn** [comment] 2016-06-30 20:51
This was a typo in `solidus_globalize` which is now fixed.

**Closed by jhawthorn** 2016-06-30 20:51 UTC
