### ISSUE TITLE
The "delivery" checkout step cannot be skipped without attaching a Shipment to the Order

### ISSUE THREAD

**Issue by travisp** [solidusio/solidus#626] opened 2015-12-28 01:52 UTC
In an app where we were looking at skipping the delivery step of the checkout process, we added the following code:

``` ruby
Spree::Order.class_eval do
  remove_checkout_step :delivery
end
```

Unfortunately, when confirming the order in the checkout process, the order fails to complete and returns with the error message `We are unable to calculate shipping rates for the selected items`. We were only able to get the checkout process to complete by assigning a Shipment to the Order as follows:

``` ruby
Spree::Order.class_eval do
  remove_checkout_step :delivery
  after_create :select_undefined_shipping

  def select_undefined_shipping
    # This allows us to skip the :delivery step
    shipment = Spree::Shipment.create(order: self, cost: 0, address: bill_address)
    shipment.add_shipping_method(Spree::ShippingMethod.undefined_shipping, true)
  end
end
```

However, this seems hacky when we don't want the delivery step to be a part of the checkout process.

**Comment by daisuke-3** [comment] 2015-12-28 02:26
I have the same issue :dango:

**Comment by Senjai** [comment] 2015-12-29 17:50
I remember this! I think create_proposed_shipments (I _believe_) has to be called. 

The one time I had to get around this we had a global zone with a $0 electronic delivery shipping method and called that method on a before_transition to payment using the order state machine, which may or may not be a better workaround for you in the time being. This was a while back now though.

I do think that this shouldn't be a problem though for stores that wish to bypass this step.

**Comment by jhawthorn** [comment] 2015-12-29 17:55
Tagging for 1.2 optimistically

**Comment by cbrunsdon** [comment] 2015-12-29 18:03
For posterity, I believe this is related to: #572

**Comment by cbrunsdon** [comment] 2015-12-29 21:54
@travisp and @daisuke-3, I'm having a conversation with @jhawthorn and we're trying to better understand exactly how you're using the checkout.

Are you looking to skip the delivery step, but still expect shipments/inventory units/etc to be created? Or are you looking to skip the step from happening, but still expect shipments etc should be created?

Also, is this something that worked previously (on spree) you're running into with Solidus, or is it an issue you're running into with a new store?

**Comment by travisp** [comment] 2015-12-30 19:38
@cbrunsdon In this particular case, this is a new Solidus store (not migrated from Spree). Our use case is somewhat unusual because we will be creating shipments, and tracking inventory, but the shipping method (and shipping address) are determined after checkout. Our approach of assigning some particular shipment that indicates an "undefined" method might be fine, but it does seem that skipping the delivery step could imply skipping the assignment of a shipment (and trying to calculate a shipping rate) altogether.

However, we were also considering Solidus for a different use case that involved digital, non-physical goods. I imagine the fact that ```remove_checkout_step :delivery``` does not work without additional effort would be a pain point for anyone trying to use Solidus to sell goods that don't have shipments, although it's certainly possible. Googling brings up a number of people who have had this use case in Spree (but were able to get it to work in older version so spree just with the remove_checkout_step).

**Comment by rbngzlv** [comment] 2016-01-08 16:06
Hi all, as @cbrunsdon said, my pull request is related to this issue.

In our case, we are skipping the delivery step of the checkout process because we are selling non-physical goods that don't have shipments.

I think that the problem is confirming the order in the checkout process, because actually is possible to bypass the delivery step, so as I commented in the pull request I think that this is a regression because in the previous versions  we only need ```remove_checkout_step :delivery``` in a decorator to skip the delivery step, without additional effort.

I copy here my comment in the pull request:

> The commit https://github.com/solidusio/solidus/commit/7ba53b2c0c9a33140f299e04541834d6fbf9ccb1#diff-2c3e70899d4f22d0569021b01b0e307f added a ```before_transition``` to ```complete``` that checks the ```shipping rates```, but if the ```delivery``` step is not present, the ```order``` doesn't have ```shipments```.

Also, @cbrunsdon made a comment in the pull request that is interesting (https://github.com/solidusio/solidus/pull/572#issuecomment-162980755). The resume is: ```What about the stores selling physical and non-physical goods?```.

I answer here for put together the two discussions:

We have a store selling physical and non-physical goods, and the "solution" that we use is to not skip the delivery step and have one ```ShippingCategory``` named ```Digital``` that only have one ```ShippingMethod``` named ```Digital delivery``` with cost zero. So in the delivery step we can have packages where the user can choice the delivery method (UPS 24h, DHL ...) and other package containing all non-physical goods where the user can not select the delivery method (we have a hidden input field with the only delivery method available, the free digital delivery).

Perhaps, we can do two steps?

- First, merge the pull request (if all is ok) to fix the regression and allow the stores selling non-physical goods to skip the delivery step.

- Second, open a new issue for search the best way to make this step optional, allowing the stores to sell physical and non-physical goods, and have the checkout with or without delivery step.

Mention me if I can help in some manner.

**Comment by mamhoff** [comment] 2017-04-22 13:36
Since #572 has been merged, I think this issue can be closed. @jhawthorn @cbrunsdon wdyt?

**Closed** 2017-10-04 22:57 UTC
