### ISSUE TITLE
[Admin] Search by name in stock

### ISSUE THREAD

**Issue by vokshirg** [solidusio/solidus#5506] opened 2023-11-07 14:59 UTC
**Solidus Version**:
4.2

**To Reproduce**
/admin/stock_items?variant_search_term=search_query&button=  
OR  
1. Go to '/admin/stock_items'
2. Try to search by any variant

**Current behavior**
exception:

```
ActiveRecord::StatementInvalid at /admin/stock_items
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...n_values"."name" ILIKE '%Sulfate-free%') ORDER BY "spree_var...
                                                             ^
```

```sql
"SELECT DISTINCT \"spree_variants\".* FROM \"spree_variants\" LEFT OUTER JOIN \"spree_products\" ON \"spree_products\".\"id\" = \"spree_variants\".\"product_id\" LEFT OUTER JOIN \"spree_option_values_variants\" ON \"spree_option_values_variants\".\"variant_id\" = \"spree_variants\".\"id\" LEFT OUTER JOIN \"spree_option_values\" ON \"spree_option_values\".\"id\" = \"spree_option_values_variants\".\"option_value_id\" WHERE \"spree_variants\".\"deleted_at\" IS NULL AND ((((\"spree_variants\".\"sku\" ILIKE '%Sulfate-free%' OR \"spree_products\".\"name\" ILIKE '%Sulfate-free%') OR \"spree_products\".\"slug\" ILIKE '%Sulfate-free%') OR \"spree_option_values\".\"presentation\" ILIKE '%Sulfate-free%') OR \"spree_option_values\".\"name\" ILIKE '%Sulfate-free%') ORDER BY \"spree_variants\".\"sku\" ASC"
```

**Expected behavior**

correct search query

**Screenshots**

![Screenshot 2023-11-07 at 15 43 13](https://github.com/solidusio/solidus/assets/10025264/57938caf-31b6-46e8-953b-e241742f7f38)

**Comment by kennyadsl** [comment] 2023-11-07 15:02
Thanks for reporting. I think the issue is here: https://github.com/solidusio/solidus/pull/3626/commits/6db4f525ce172428d3a78cd7099d5993510b2666#r1383302271. We tried and by removing the `.distinct`call the error disappear.  

cc @softr8 

This might be a good first contribution if anyone is interested.

**Comment by vokshirg** [comment] 2023-11-07 15:24
Temp Hotfix for anybody else

```ruby
# app/overrides/hairdom/controllers/spree/admin/stock_items_controller/fix_search.rb
module Hairdom
  module Spree
    module Admin
      module StockItemsController
        module FixSearch
          def variant_scope
            scope = ::Spree::Variant
                      .accessible_by(current_ability)
                      .order(:sku)
                      .includes(
                        :images,
                        stock_items: :stock_location,
                        product: :variant_images,
                        option_values: :option_type
                      )

            scope = scope.where(product: @product, is_master: !@product.has_variants?) if @product
            scope = scope.by_stock_location(params[:stock_location_id]) if params[:stock_location_id].present?

            scope
          end

          ::Spree::Admin::StockItemsController.prepend self
        end
      end
    end
  end
end
```

**Comment by mehboobali98** [comment] 2023-11-09 08:43
Can I work on this? Thanks

**Comment by kennyadsl** [comment] 2023-11-09 10:57
@mehboobali98 you are welcome!

**Comment by FranciscoJBrito** [comment] 2023-11-25 15:23
Hi @kennyadsl @vokshirg, is this issue still open? To work on it

**Comment by kennyadsl** [comment] 2023-11-27 19:03
@FranciscoJBrito yes!

**Comment by nvandoorn** [comment] 2024-02-13 17:33
Hey folks, I opened #5660 to address this. I don't think it's complete yet, so I marked it as draft, but at the minimum it has a useful feature spec.

**Closed** 2024-02-14 09:40 UTC
Labels: type:bug, good first issue, confirmed
