### ISSUE TITLE
Edit promotions page - rules for users

### ISSUE THREAD

**Issue by simo163** [solidusio/solidus#1352] opened 2016-07-25 09:35 UTC
Hello,

I found a little issue when loading the edit promotion page, initializing the users into the rules if existing requires the API key access. I send a small PR for it. Kind regards!

**Comment by jeremyw** [comment] 2016-07-25 22:27
See #1350. The issue is not the API key but the params.

**Comment by jhawthorn** [comment] 2016-08-03 20:08
Duplicate of #1350

**Closed by jhawthorn** 2016-08-03 20:08 UTC
Labels: duplicate

**Comment by joelind** [comment] 2016-08-12 12:45
Actually, there *is* an API key issue. When you go to edit an existing promotion with a user rule, the box that is supposed to list the users is empty. It appears that the UI is trying to fetch the users by ID, but it gets a 401 (since this API request has no token in it). See attached. I'm working on a PR for this.

<img width="1257" alt="screen shot 2016-08-12 at 8 44 16 am" src="https://cloud.githubusercontent.com/assets/39476/17622564/20695f1a-6069-11e6-87dc-e69b9486e584.png">

**Comment by jasonfb** [comment] 2016-08-12 13:16
@joelind -- are you certain you generated your own API key for the user you are logged in with? You do this by searching for yourself on the "Users" tab and then hit "Generate API Key" on your own page (This is associated with the Admin user you are logged in with)

Generally all Admins need API keys

**Comment by joelind** [comment] 2016-08-12 13:27
@jasonfb yes. The `initSelection` option that is passed to `select2` does a raw jQuery get, which doesn't seem to be sending the api_key with it. If I change the following, it works. Am I missing something?

If I edit `user_picker.js`, to change ```
 11     initSelection: function (element, callback) {
 12       $.get(Spree.routes.users_api, {
 13         ids: element.val()
 14       }, function (data) {
 15         callback(data.users);
 16       });
 17     },
```

to ```
 11     initSelection: function (element, callback) {
 12       $.ajax({
 13         url: Spree.routes.users_api,
 14         data: { ids: element.val() },
 15         headers: { "X-Spree-Token": Spree.api_key },
 16         success: function (data) {
 17           callback(data.users);
 18         }
 19       });
 20     },
```

**Comment by simo163** [comment] 2016-08-16 13:09
@joelind Thanks for explaining it better, this is exactly what I meant. I sent a PR for it in case #1353
