### ISSUE TITLE
Edit path for completed orders

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus#2078] opened 2017-07-11 23:10 UTC
If I visit the path of a completed order, e.g., `http://localhost:3000/orders/R465318167`, I can see a receipt of the order. If I then append `edit` to that, and navigate to `http://localhost:3000/orders/R465318167/edit`, I am shown the Cart page.

This is unexpected behavior, IMO. I’d expect to either be able to edit the order (i.e., change address or cancel or something like that), _or_ to be told that I can’t edit this order because it’s locked or finalized, etc.

But seeing the current_order Cart page rendered at the `/edit` URL of a completely different order is definitely not expected!

**Comment by jasonfb** [comment] 2017-07-11 23:16
Spam detection software, running on the system "mail2.hsphere.cc", has
identified this incoming email as possible spam.  The original message
has been attached to this so you can view it (if it isn't spam) or label
similar future email.  If you have any questions, see
the administrator of that system for details.

Content preview:  What order state (cart, address, payment, etc) of the order
   in your test environment? Is it completed or not? Sent from my iPhone [...]
   

Content analysis details:   (6.6 points, 5.0 required)

 pts rule name              description
---- ---------------------- --------------------------------------------------
 1.6 WEIRD_PORT             URI: Uses non-standard port number for HTTP
 0.0 HTML_MESSAGE           BODY: HTML included in message
 2.4 HTML_IMAGE_ONLY_32     BODY: HTML: images with 2800-3200 bytes of words
 2.5 MIME_QP_LONG_LINE      RAW: Quoted-printable line longer than 76 chars
 0.1 RDNS_NONE              Delivered to trusted network by a host with no rDNS

The original message was not completely plain text, and may be unsafe to
open with some email clients; in particular, it may contain a virus,
or confirm that your address can receive spam.  If you wish to view
it, it may be safer to save it to a file and open it with an editor.


X-Virus-Scan: Scanned by ClamAV 0.98.4 (no viruses);
  Tue, 11 Jul 2017 19:15:58 -0400
Received: from unknown (HELO ?100.73.27.195?) (jason.fb@datatravels.com@70.214.73.46)
  (de-)crypted with TLSv1: DHE-RSA-AES256-SHA [256/256] DN=unknown
  by mail2.hsphere.cc with ESMTPSAM; 11 Jul 2017 23:15:57 -0000
X-Originating-IP: 70.214.73.46
Content-Type: multipart/alternative;
	boundary=Apple-Mail-AA74E3D0-3871-4AE3-B9C3-5EF656BDECB2
Mime-Version: 1.0 (1.0)
Subject: Re: [solidusio/solidus] Edit path for completed orders (#2078)
From: Jason FB <jason.fb@datatravels.com>
X-Mailer: iPhone Mail (14F89)
In-Reply-To: <solidusio/solidus/issues/2078@github.com>
Date: Tue, 11 Jul 2017 19:15:51 -0400
Content-Transfer-Encoding: 7bit
Message-Id: <41F4AAD9-A641-46B6-89A6-25090D767BA1@datatravels.com>
References: <solidusio/solidus/issues/2078@github.com>
To: solidusio/solidus <reply@reply.github.com>


--Apple-Mail-AA74E3D0-3871-4AE3-B9C3-5EF656BDECB2
Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

What order state (cart, address, payment, etc) of the order in your test env=
ironment?

Is it completed or not?

Sent from my iPhone

> On Jul 11, 2017, at 7:10 PM, brchristian <notifications@github.com> wrote:=

>=20
> If I visit the path of a completed order, e.g., http://localhost:3000/orde=
rs/R465318167, I can see a receipt of the order. If I then append edit to th=
at, and navigate to http://localhost:3000/orders/R465318167/edit, I am shown=
 the Cart page.
>=20
> This is unexpected behavior, IMO. I=E2=80=99d expect to either be able to e=
dit the order (i.e., change address or cancel or something like that), or to=
 be told that I can=E2=80=99t edit this order because it=E2=80=99s locked or=
 finalized, etc.
>=20
> But seeing the current_order Cart page rendered at the /edit URL of a comp=
letely different order is definitely not expected!
>=20
> =E2=80=94
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>=20

--Apple-Mail-AA74E3D0-3871-4AE3-B9C3-5EF656BDECB2
Content-Type: text/html;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"content-type" content=3D"text/html; charset=3D=
utf-8"></head><body dir=3D"auto"><div>What order state (cart, address, payme=
nt, etc) of the order in your test environment?</div><div id=3D"AppleMailSig=
nature"><br></div><div id=3D"AppleMailSignature">Is it completed or not?<br>=
<br>Sent from my iPhone</div><div><br>On Jul 11, 2017, at 7:10 PM, brchristi=
an &lt;<a href=3D"mailto:notifications@github.com">notifications@github.com<=
/a>&gt; wrote:<br><br></div><blockquote type=3D"cite"><div><p>If I visit the=
 path of a completed order, e.g., <code><a href=3D"http://localhost:3000/ord=
ers/R465318167">http://localhost:3000/orders/R465318167</a></code>, I can se=
e a receipt of the order. If I then append <code>edit</code> to that, and na=
vigate to <code><a href=3D"http://localhost:3000/orders/R465318167/edit">htt=
p://localhost:3000/orders/R465318167/edit</a></code>, I am shown the Cart pa=
ge.</p>
<p>This is unexpected behavior, IMO. I=E2=80=99d expect to either be able to=
 edit the order (i.e., change address or cancel or something like that), <em=
>or</em> to be told that I can=E2=80=99t edit this order because it=E2=80=99=
s locked or finalized, etc.</p>
<p>But seeing the current_order Cart page rendered at the <code>/edit</code>=
 URL of a completely different order is definitely not expected!</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">=E2=80=
=94<br>You are receiving this because you are subscribed to this thread.<br>=
Reply to this email directly, <a href=3D"https://github.com/solidusio/solidu=
s/issues/2078">view it on GitHub</a>, or <a href=3D"https://github.com/notif=
ications/unsubscribe-auth/AADmetEg8pBhYikygkrPyM2PAkrDT3zcks5sNADJgaJpZM4OU7=
W4">mute the thread</a>.<img alt=3D"" height=3D"1" src=3D"https://github.com=
/notifications/beacon/AADmeupdFbsO9Ob52hPJn0-RV7EiITrkks5sNADJgaJpZM4OU7W4.g=
if" width=3D"1"></p>
<div itemscope=3D"" itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope=3D"" itemtype=3D"http://schema.org/ViewAc=
tion">
  <link itemprop=3D"url" href=3D"https://github.com/solidusio/solidus/issues=
/2078">
  <meta itemprop=3D"name" content=3D"View Issue">
</div>
<meta itemprop=3D"description" content=3D"View this Issue on GitHub">
</div>

<script type=3D"application/json" data-scope=3D"inboxmarkup">{"api_version":=
"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitH=
ub"},"entity":{"external_key":"github/solidusio/solidus","title":"solidusio/=
solidus","subtitle":"GitHub repository","main_image_url":"https://cloud.gith=
ubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb=
5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418=
/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open i=
n GitHub","url":"https://github.com/solidusio/solidus"}},"updates":{"snippet=
s":[{"icon":"DESCRIPTION","message":"Edit path for completed orders (#2078)"=
}],"action":{"name":"View Issue","url":"https://github.com/solidusio/solidus=
/issues/2078"}}}</script></div></blockquote></body></html>=

--Apple-Mail-AA74E3D0-3871-4AE3-B9C3-5EF656BDECB2--

**Comment by mamhoff** [comment] 2017-07-14 18:40
@jasonfb There was a comment here that was almost impossible to read, and I'm not even sure it wasn't a spam filter overreacting. Would you mind posting your answer again?

**Comment by kennyadsl** [comment] 2018-10-01 11:04
I think we should just put a flash message that inform the user that the order is not editable.

**Comment by JDutil** [comment] 2018-10-11 22:47
@kennyadsl was just looking at this for Hacktoberfest, and I think this may already be resolved in that I can't reproduce that behavior on master. I don't see any flash message it just redirects me to the shipments not the cart.

**Comment by potomak** [comment] 2018-10-19 19:02
I'm running the app locally (master) and I don't see the point of exposing the `edit` action on the route `GET /orders/:id/edit`. That action doesn't search for any particular order by id as `show` does.

> I think we should just put a flash message that inform the user that the order is not editable.

If possible I think it would be just easier to exclude the `edit` action from `resources :orders`. What do you think about this approach?

**Comment by kennyadsl** [comment] 2018-10-19 20:47
> If possible I think it would be just easier to exclude the edit action from resources :orders. What do you think about this approach?

It makes sense for me. 👍  

I think that route is there since there are stores that allow changing orders info after purchase but they can just add that route back and customize `Spree::OrdersController#edit`.

**Comment by JDutil** [comment] 2018-10-23 22:06
I don’t think it’s an easier approach although I did like the idea.

I just briefly tried removing the controller action and route, and it effected a lot of places currently using the route helper.  I imagine many extensions or applications are still using the route as well.

The simpler solution would be the flash message and redirect even if it’s not as nice.

How exactly did you reproduce this issue?  Perhaps I’m missing something, but I didn’t see the problem when I tried. My orders must be in a different state than expected to reproduce the issue.

**Closed** 2019-11-07 14:22 UTC
Labels: Hacktoberfest
