### ISSUE TITLE
Using ajax to get home is slower than standard request

### ISSUE THREAD

**Issue by sebfie** [solidusio/solidus#1639] opened 2016-12-05 10:24 UTC
Hello,

I have an issue with solidus, I am creating an add on to edit cms content of solidus and I need to get home using ajax. 

Using ajax it tooks 1.9sec

```
Started HEAD "/" for 127.0.0.1 at 2016-12-05 11:17:30 +0100
Processing by Spree::HomeController#index as */*
  Spree::Store Load (0.3ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."code" = $1 LIMIT $2  [["code", "127.0.0.1"], ["LIMIT", 1]]
  Spree::Store Load (0.4ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE (url like '%127.0.0.1%') ORDER BY "spree_stores"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Spree::Store Load (0.4ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."default" = $1 ORDER BY "spree_stores"."id" ASC LIMIT $2  [["default", true], ["LIMIT", 1]]
  Rendering /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/home/index.html.erb within spree/layouts/spree_application
  Spree::Taxonomy Load (0.4ms)  SELECT "spree_taxonomies".* FROM "spree_taxonomies" ORDER BY "spree_taxonomies"."position" ASC
  Spree::Taxon Load (0.4ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL AND "spree_taxons"."taxonomy_id" IN (1, 2)
  Spree::Taxon Load (0.5ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IN (2, 1) ORDER BY "spree_taxons"."lft"
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_taxonomies.html.erb (7.0ms)
   (3.1ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
   (3.0ms)  SELECT  DISTINCT MAX("spree_products"."updated_at") FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
   (2.8ms)  SELECT DISTINCT COUNT(DISTINCT "spree_products"."id") FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL  [["is_master", true], ["currency", "USD"]]
  CACHE (0.0ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  CACHE (0.0ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  Spree::Product Load (3.4ms)  SELECT  DISTINCT "spree_products".* FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:17:30.985637') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  Spree::Variant Load (0.5ms)  SELECT "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."is_master" = $1 AND "spree_variants"."product_id" IN (8, 1, 9, 2, 4, 3, 7, 5, 6)  [["is_master", true]]
  Spree::Price Load (0.5ms)  SELECT "spree_prices".* FROM "spree_prices" WHERE "spree_prices"."deleted_at" IS NULL AND "spree_prices"."is_default" = $1 AND "spree_prices"."variant_id" IN (3, 4, 8, 5, 9, 7, 6, 1, 2) ORDER BY country_iso IS NULL  [["is_default", true]]
  Spree::Image Load (0.7ms)  SELECT "spree_assets".* FROM "spree_assets" WHERE "spree_assets"."type" IN ('Spree::Image') AND "spree_assets"."viewable_type" = $1 AND "spree_assets"."viewable_id" IN (8, 1, 9, 2, 4, 3, 7, 5, 6) ORDER BY "spree_assets"."position" ASC  [["viewable_type", "Spree::Variant"]]
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_products.html.erb (89.0ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/home/index.html.erb within spree/layouts/spree_application (392.4ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_head.html.erb (58.9ms)
Deface: 1 overrides found for 'spree/shared/_nav_bar'
Deface: 'auth_shared_login_bar' matched 1 times with 'li#search-bar'
Deface: [ERROR] The original source for 'auth_shared_login_bar' has changed, this override should be reviewed to ensure it's still valid.
   (0.6ms)  SELECT MAX("spree_taxons"."updated_at") FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL
  Spree::Taxon Load (0.5ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL ORDER BY "spree_taxons"."lft"
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_search.html.erb (4.5ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_nav_bar.html.erb (146.6ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_main_nav_bar.html.erb (1.1ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_header.html.erb (437.3ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_sidebar.html.erb (0.6ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_footer.html.erb (0.6ms)
  Spree::Tracker Load (0.5ms)  SELECT  "spree_trackers".* FROM "spree_trackers" WHERE "spree_trackers"."active" = $1 ORDER BY "spree_trackers"."id" ASC LIMIT $2  [["active", true], ["LIMIT", 1]]
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_google_analytics.html.erb (2.3ms)
Completed 200 OK in 1912ms (Views: 1747.1ms | ActiveRecord: 18.1ms)
```

Using browser 377ms : 

```
Started GET "/" for 127.0.0.1 at 2016-12-05 11:16:56 +0100
Processing by Spree::HomeController#index as HTML
  Spree::Store Load (0.4ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."code" = $1 LIMIT $2  [["code", "127.0.0.1"], ["LIMIT", 1]]
  Spree::Store Load (0.5ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE (url like '%127.0.0.1%') ORDER BY "spree_stores"."id" ASC LIMIT $1  [["LIMIT", 1]]
  Spree::Store Load (0.5ms)  SELECT  "spree_stores".* FROM "spree_stores" WHERE "spree_stores"."default" = $1 ORDER BY "spree_stores"."id" ASC LIMIT $2  [["default", true], ["LIMIT", 1]]
  Rendering /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/home/index.html.erb within spree/layouts/spree_application
  Spree::Taxonomy Load (0.4ms)  SELECT "spree_taxonomies".* FROM "spree_taxonomies" ORDER BY "spree_taxonomies"."position" ASC
  Spree::Taxon Load (0.6ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL AND "spree_taxons"."taxonomy_id" IN (1, 2)
  Spree::Taxon Load (0.5ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IN (2, 1) ORDER BY "spree_taxons"."lft"
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_taxonomies.html.erb (7.2ms)
   (3.7ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
   (2.7ms)  SELECT  DISTINCT MAX("spree_products"."updated_at") FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
   (2.8ms)  SELECT DISTINCT COUNT(DISTINCT "spree_products"."id") FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL  [["is_master", true], ["currency", "USD"]]
  CACHE (0.0ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  CACHE (0.0ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT "spree_products"."id" AS count_column FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4) subquery_for_count  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  Spree::Product Load (3.5ms)  SELECT  DISTINCT "spree_products".* FROM "spree_products" INNER JOIN "spree_variants" ON "spree_variants"."product_id" = "spree_products"."id" AND "spree_variants"."is_master" = $1 AND "spree_variants"."deleted_at" IS NULL INNER JOIN "spree_prices" ON "spree_prices"."variant_id" = "spree_variants"."id" AND "spree_prices"."deleted_at" IS NULL INNER JOIN "spree_variants" "variants_including_masters_spree_products_join" ON "variants_including_masters_spree_products_join"."product_id" = "spree_products"."id" AND "variants_including_masters_spree_products_join"."deleted_at" IS NULL INNER JOIN "spree_prices" "prices_spree_products" ON "prices_spree_products"."variant_id" = "variants_including_masters_spree_products_join"."id" AND "prices_spree_products"."deleted_at" IS NULL WHERE "spree_products"."deleted_at" IS NULL AND ("spree_products".available_on <= '2016-12-05 10:16:56.275537') AND "spree_prices"."deleted_at" IS NULL AND "spree_prices"."currency" = $2 AND "spree_prices"."country_iso" IS NULL LIMIT $3 OFFSET $4  [["is_master", true], ["currency", "USD"], ["LIMIT", 12], ["OFFSET", 0]]
  Spree::Variant Load (0.7ms)  SELECT "spree_variants".* FROM "spree_variants" WHERE "spree_variants"."is_master" = $1 AND "spree_variants"."product_id" IN (8, 1, 9, 2, 4, 3, 7, 5, 6)  [["is_master", true]]
  Spree::Price Load (0.6ms)  SELECT "spree_prices".* FROM "spree_prices" WHERE "spree_prices"."deleted_at" IS NULL AND "spree_prices"."is_default" = $1 AND "spree_prices"."variant_id" IN (3, 4, 8, 5, 9, 7, 6, 1, 2) ORDER BY country_iso IS NULL  [["is_default", true]]
  Spree::Image Load (0.7ms)  SELECT "spree_assets".* FROM "spree_assets" WHERE "spree_assets"."type" IN ('Spree::Image') AND "spree_assets"."viewable_type" = $1 AND "spree_assets"."viewable_id" IN (8, 1, 9, 2, 4, 3, 7, 5, 6) ORDER BY "spree_assets"."position" ASC  [["viewable_type", "Spree::Variant"]]
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_products.html.erb (74.8ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/home/index.html.erb within spree/layouts/spree_application (125.9ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_head.html.erb (62.6ms)
Deface: 1 overrides found for 'spree/shared/_nav_bar'
Deface: 'auth_shared_login_bar' matched 1 times with 'li#search-bar'
Deface: [ERROR] The original source for 'auth_shared_login_bar' has changed, this override should be reviewed to ensure it's still valid.
   (0.5ms)  SELECT MAX("spree_taxons"."updated_at") FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL
  Spree::Taxon Load (0.3ms)  SELECT "spree_taxons".* FROM "spree_taxons" WHERE "spree_taxons"."parent_id" IS NULL ORDER BY "spree_taxons"."lft"
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_search.html.erb (3.9ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_nav_bar.html.erb (19.1ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_main_nav_bar.html.erb (0.7ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_header.html.erb (58.4ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_sidebar.html.erb (13.2ms)
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_footer.html.erb (0.7ms)
  Spree::Tracker Load (0.5ms)  SELECT  "spree_trackers".* FROM "spree_trackers" WHERE "spree_trackers"."active" = $1 ORDER BY "spree_trackers"."id" ASC LIMIT $2  [["active", true], ["LIMIT", 1]]
  Rendered /Users/sebfie/.rvm/gems/ruby-2.3.0/gems/solidus_frontend-2.0.0/app/views/spree/shared/_google_analytics.html.erb (2.5ms)
Completed 200 OK in 377ms (Views: 338.7ms | ActiveRecord: 19.4ms)
```

In production mode, it does not happen.

Any idea?

**Comment by mtomov** [comment] 2016-12-06 16:10
It is difficult to measure something like that in development because classes are reloaded and assets might be re-compiled on the fly in development. There should be comments in your Rails's `environments/development.rb` that explain that for `cache_classes`, `eager_load` .. etc. 

Also, did you try the Ajax multiple times ? Might be that one some of the subsequent calls it will have all loaded .. and it will give you a similar sub half-second response.

**Comment by sebfie** [comment] 2016-12-06 16:11
Hello,

Yes, multi times get the same result. Did you reproduce it?

**Comment by did** [comment] 2016-12-06 16:23
hey @mtomov, thanks for the quick reply. In dev, I get the same odd behaviour with both a request from curl and an AJAX request from the browser. The logs look the same compared to a simple GET request from the browser, except that it takes way more time to render some partials (it's totally random, not always the same) with an AJAX/curl request.
I wonder if other developers noticed that behaviour, especially when Solidus is used with Turbolinks in development.
However, in production, the rendering times are the same.

**Comment by jhawthorn** [comment] 2016-12-06 22:24
I've seen this before.

I believe what's happening is that the different `Accept` headers for content type make the rendering slower. I would guess (but can't confirm) that this is due to template lookup with multiple formats.

I can reproduce locally from a fresh sandbox, though my differences are far less pronounced:

`time curl -I -H 'Accept: text/html' http://localhost:3000/` 0.128 seconds
`time curl -I -H 'Accept: */*' http://localhost:3000/` 0.290 seconds

This seems to be the case in a standard rails app as well.

Closing this since I don't think there's anything we can do in Solidus to improve this (rails issue afaict), and it doesn't affect production.

**Closed by jhawthorn** 2016-12-06 22:24 UTC

**Comment by did** [comment] 2016-12-06 22:30
hey @jhawthorn, good catch man, you nailed it! thanks!
