### ISSUE TITLE
Product List Not Showing Up in Admin/Orders After Successful Checkout

### ISSUE THREAD

**Issue by jittdev** [solidusio/solidus#2938] opened 2018-11-09 18:41 UTC
### Steps to reproduce
1. On a clean install, Login as Admin. Rename Demo Store to your own name. Add at least one of your own products (then delete Demo/Example Store products).  Set up other necessary items (zones, payments..
2. With a different user submit an order successfully.
3. As admin, Select Orders. View the order you just created.
4. Voila', No Product List

### Expected behavior
On 4., there should be a Product list that says something like "R12345678 Pending Package from default", with the ordered products listed below (and options for each product to the right).

### Actual behavior
Instead, under Shipments, Add Product, Line item adjustments, Shipment adjustments are there, but no actual Line Items (products).

### System configuration
**Solidus Version**: 2.7.0
Mac OS High Sierra 10.13.6
Safari: 12.0.1
Rails 5.2.1
![screen shot 2018-11-09 at 11 26 49 am](https://user-images.githubusercontent.com/38799486/48281540-7e101300-e41c-11e8-8104-3eb7b89a481d.png)

Any help with this would be greatly appreciated. (on a side note, how come there is nowhere for a user (not admin) to log out of the session?). Thanks.

**Extensions in use**:

**Comment by jacobherrington** [comment] 2018-11-09 20:28
I'm not able to reproduce this, but that doesn't mean there isn't a bug.

To logout just go to `localhost:3000/logout`. In the example frontend there is also a link if you're logged in:

![84da33cb-968b-4dd6-98b9-21171791b20a](https://user-images.githubusercontent.com/11466782/48286568-aeab7900-e42b-11e8-9810-5243f5b7fa69.png)

**Comment by seand7565** [comment] 2020-05-23 15:35
Since we haven't received any confirmation on this issue, and given the date, can we close this?

**Comment by jarednorman** [comment] 2020-05-24 21:01
Closing since we were unable to confirm this and it's been ages since the last update.

**Closed by jarednorman** 2020-05-24 21:01 UTC
Labels: Unconfirmed
