### ISSUE TITLE
fresh installation: undefined method `register_engine' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by krtschmr** [solidusio/solidus#642] opened 2016-01-01 11:51 UTC
rails new demostore -d mysql
    rails g migration my_first_mygration

so rails can't boot as soon i add
    gem 'solidus' 
to my Gemfile

    /home/tim/.rvm/gems/ruby-2.1.6/gems/handlebars_assets-0.19.1/lib/handlebars_assets.rb:20:in `block in register_extensions': undefined method `register_engine' for nil:NilClass (NoMethodError)

bundle show | grep solidus

       * solidus (1.1.0)
       * solidus_api (1.1.0)
       * solidus_backend (1.1.0)
       * solidus_core (1.1.0)
       * solidus_frontend (1.1.0)
       * solidus_sample (1.1.0)

**Comment by krtschmr** [comment] 2016-01-01 11:59
ruby 2.1.6
rails 4.2.4

**Comment by krtschmr** [comment] 2016-01-01 12:32
solidus 1.0.3 is working (but somehow i tagged gemfile with v1.0 but got 1.03)

**Comment by cbrunsdon** [comment] 2016-01-04 20:04
Aye, duplicate of #598, fixed in published release and master.

**Closed by cbrunsdon** 2016-01-04 20:04 UTC
