### ISSUE TITLE
Missing add_routes method updating solidus to 2.1.0

### ISSUE THREAD

**Issue by sechix** [solidusio/solidus#1687] opened 2017-01-19 15:47 UTC
Run server I get error due to missing method in spree:core: 'add_routes' .

This method is used in routes.rb file of extensions solidus_social or solidus_reviews
gem 'solidus_reviews', github: 'solidusio-contrib/solidus_reviews'
gem 'solidus_social' , github: 'solidusio-contrib/solidus_social'

Solidus_reviews/config/routes.rb

`
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  resources :products, only: [] do
    resources :reviews, only: [:index, :new, :create] do
    end
  end
  post '/reviews/:review_id/feedback(.:format)' => 'feedback_reviews#create', as: :feedback_reviews
end`

**Comment by tvdeyen** [comment] 2017-01-19 15:51
This can be solved by using `Spree::Core::Engine.routes.draw`

This issue is a duplicate of https://github.com/solidusio-contrib/solidus_reviews/issues/5 and should be solved at that extension

**Closed by tvdeyen** 2017-01-19 15:51 UTC

**Comment by sechix** [comment] 2017-01-19 17:25
ok
